In [1]:
import pandas as pd
import numpy as np

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [13]:
ser1 = pd.Series([0,1,2], index=['X', 'Y', 'Z'], name='ser1')

In [16]:
ser2 = pd.Series([2,3,4], index=['X', 'Y', 'Z'], name='ser2')

In [17]:
pd.concat([ser1, ser2], axis=1, sort=True)

ser1  ser2
X     0     2
Y     1     3
Z     2     4

In [20]:
df1 = pd.DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])

df2 = pd.DataFrame(np.random.randn(3,3), columns=['X', 'A', 'Y'])

In [22]:
df1

X         Y         Z
0  0.796406 -0.067039  0.086180
1 -0.279765  1.113494 -1.108988
2  0.033058  0.846702  0.851346
3 -1.616842 -0.449375 -0.914097

In [23]:
df2

X         A         Y
0  0.911602 -0.512702  0.952853
1  0.561909  0.975123  0.587858
2  1.481039 -1.315721 -0.495026

In [27]:
pd.concat([df1, df2], axis=0, sort=True, ignore_index=True)

A         X         Y         Z
0       NaN  0.796406 -0.067039  0.086180
1       NaN -0.279765  1.113494 -1.108988
2       NaN  0.033058  0.846702  0.851346
3       NaN -1.616842 -0.449375 -0.914097
4 -0.512702  0.911602  0.952853       NaN
5  0.975123  0.561909  0.587858       NaN
6 -1.315721  1.481039 -0.495026       NaN