In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('my_array', arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('my_array.npy')
arr1

array([0, 1, 2, 3, 4])

In [9]:
arr2 = arr.copy()

In [11]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.savez('zip_array.npz', x=arr1, y=arr2)

In [15]:
archive_arr = np.load('zip_array.npz')

In [17]:
archive_arr['x'], archive_arr['y']

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [18]:
np.savez('zip_array2.npz', arr1, arr2)

In [19]:
archive_arr2 = np.load('zip_array2.npz')

In [21]:
archive_arr2.keys()

['arr_1', 'arr_0']

In [24]:
arr = np.array([[1,2,3], [4,5,6]])

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.savetxt('my_text_array.txt', arr, delimiter=',')

In [32]:
arr = np.loadtxt('my_text_array.txt', delimiter=',')

In [33]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])