In [1]:
import numpy as np

In [8]:
my_list1 = [1,2,3,4]

In [9]:
my_array1 = np.array(my_list1)

In [10]:
my_array1

array([1, 2, 3, 4])

In [11]:
my_list2 = [11,22,33,44]

In [12]:
my_lists = [my_list1, my_list2]

In [13]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [14]:
my_array2 = np.array(my_lists)

In [32]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [16]:
my_array2.shape

(2, 4)

In [17]:
my_array2.dtype

dtype('int64')

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.ones([1,5])

array([[1., 1., 1., 1., 1.]])

In [28]:
# Random values
np.empty([3,5])

array([[4.65444614e-310, 4.65444596e-310, 6.94974905e-310,
        6.94974900e-310, 6.94974900e-310],
       [6.94974900e-310, 5.53353523e-322, 2.37151510e-322,
        4.65444614e-310, 6.94974904e-310],
       [6.94974904e-310, 6.94974900e-310, 6.94974906e-310,
        4.00193173e-322, 4.65444603e-310]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.arange(5, 15, )

TypeError: arange() argument after * must be an iterable, not int