In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[3]

3

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [8]:
arr[0:3] = 1

In [9]:
arr

array([ 1,  1,  1,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.arange(0,11)

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [36]:
slice_of_arr = slice_of_arr[::-1]

In [40]:
slice_of_arr[:]

array([4, 4, 3, 2, 1, 4])

In [38]:
slice_of_arr[0] = 4

In [41]:
arr

array([ 4,  4,  3,  2,  1,  4,  6,  7,  8,  9, 10])

In [43]:
arr_copy = arr.copy()

In [44]:
arr_copy

array([ 4,  4,  3,  2,  1,  4,  6,  7,  8,  9, 10])

In [45]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [48]:
arr_2d[0:3]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
arr_2d[1][0]

20

In [50]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [54]:
print arr_2d[2:] 
# Returns a 2D array
# because [2:] needs an iterable to iterate
# [2:] means 2 index and further 
print arr_2d[2]
# Returns a 1D array
# because [2] just tells the element 
# [2] just means the second element

[[35 40 45]]
[35 40 45]


In [55]:
arr2d = np.zeros((10,10))

In [56]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
arr_length  = arr2d.shape[0]

In [59]:
arr_length

10

In [62]:
for i in range(arr_length):
    arr2d[i] = i

In [84]:
for i in range(10):
    for j in range(10):
        arr2d[i, j] = i+j

In [86]:
print arr2d

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
 [ 8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]]


In [88]:
print arr2d[[2,3,6]]

[[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]]


In [100]:
print arr2d[3:6, 4:7]

[[ 7.  8.  9.]
 [ 8.  9. 10.]
 [ 9. 10. 11.]]
