In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([-1.15546671, -0.29543442, -0.58532153,  0.42208287,  0.58158932,
        1.28212179, -0.52378057, -0.59296856, -0.44332189, -0.80325702])

In [9]:
B = np.random.randn(10)

In [10]:
B

array([ 1.42517768, -0.83731301,  1.41314688,  1.27603909,  0.40897387,
       -1.41538261, -0.15567199,  0.7642788 , -0.7085011 ,  0.77066819])

In [11]:
# Binary Functions
np.add(A, B)

array([ 0.26971097, -1.13274743,  0.82782535,  1.69812195,  0.99056319,
       -0.13326083, -0.67945256,  0.17131023, -1.15182299, -0.03258882])

In [13]:
np.maximum(A,B)

array([ 1.42517768, -0.29543442,  1.41314688,  1.27603909,  0.58158932,
        1.28212179, -0.15567199,  0.7642788 , -0.44332189,  0.77066819])